# Generated by Django 5.2 on 2025-04-25 05:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typemarche',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='test', editable=False, populate_from='nom'),
            preserve_default=False,
        ),
    ]
