# Generated by Django 5.2 on 2025-04-25 06:19

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_typemarche_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typemarche',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='nom', unique=True),
        ),
    ]
