# Generated by Django 5.2 on 2025-05-15 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_typemarche_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet_appel', models.TextField()),
                ('maitre_ouvrage', models.CharField(max_length=300)),
                ('denomination', models.CharField(max_length=30)),
                ('commission_marche', models.CharField(max_length=200)),
                ('type_dossier', models.CharField(max_length=100)),
                ('numero_dossier', models.IntegerField(blank=True, null=True)),
                ('exercice_budgetaire', models.IntegerField()),
                ('financement', models.CharField(max_length=300)),
                ('imputation', models.CharField(max_length=200)),
                ('type_marche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='document.typemarche')),
            ],
        ),
    ]
