# Generated by Django 5.2 on 2025-05-26 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_appeloffre_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('nom_composant', models.CharField(max_length=100)),
                ('type_marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.typemarche')),
            ],
        ),
    ]
