# Generated by Django 5.2 on 2025-05-26 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_piece'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='nom',
            new_name='titre',
        ),
    ]
