# Generated by Django 5.2 on 2025-05-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_rename_nom_piece_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffre',
            name='mode_passation',
            field=models.CharField(default='ouvert', max_length=10),
            preserve_default=False,
        ),
    ]
