# Generated by Django 5.2 on 2025-06-07 22:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_piece_statut_statutpiece'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffre',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
