# Generated by Django 5.2 on 2025-06-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_appeloffre_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeloffre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
