# Generated by Django 5.2 on 2025-06-07 23:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_alter_appeloffre_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeloffre',
            name='created_at',
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='date_creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
