# Generated by Django 5.2 on 2026-05-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_remove_appeloffre_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffre',
            name='departement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_moa'),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appeloffre',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
