# Generated by Django 5.2 on 2025-06-10 14:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvisAppelOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet_appel', ckeditor.fields.RichTextField()),
                ('consistence_travaux', ckeditor.fields.RichTextField()),
                ('tranches', ckeditor.fields.RichTextField()),
                ('cout_previsionnel', ckeditor.fields.RichTextField()),
                ('delai_previsionnel', ckeditor.fields.RichTextField()),
                ('participation', ckeditor.fields.RichTextField()),
                ('financement', ckeditor.fields.RichTextField()),
                ('mode_soumission', models.CharField(max_length=100)),
                ('caution_soumission', ckeditor.fields.RichTextField()),
                ('consultation_dossier', ckeditor.fields.RichTextField()),
                ('acquition_dao', ckeditor.fields.RichTextField()),
                ('remise_offre', ckeditor.fields.RichTextField()),
                ('recevabilite_plis', ckeditor.fields.RichTextField()),
                ('ouverture_plis', ckeditor.fields.RichTextField()),
                ('critere_eliminatoire', ckeditor.fields.RichTextField()),
                ('critere_essenetielles', ckeditor.fields.RichTextField()),
                ('attribution', ckeditor.fields.RichTextField()),
                ('nombre_max_lots', models.IntegerField()),
                ('duree_validite', models.IntegerField()),
                ('renseignement_complementaires', ckeditor.fields.RichTextField()),
                ('numero_moa', models.IntegerField()),
            ],
        ),
    ]
