# Generated by Django 5.2 on 2025-06-10 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_travaux', '0001_initial'),
        ('document', '0012_remove_appeloffre_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisappeloffre',
            name='appel_offre',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='document.appeloffre'),
            preserve_default=False,
        ),
    ]
