# Generated by Django 5.2 on 2025-06-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_travaux', '0002_avisappeloffre_appel_offre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avisappeloffre',
            old_name='critere_essenetielles',
            new_name='critere_essentielles',
        ),
    ]
