# Generated by Django 5.2 on 2025-06-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_travaux', '0003_rename_critere_essenetielles_avisappeloffre_critere_essentielles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avisappeloffre',
            old_name='acquition_dao',
            new_name='acquisition_dao',
        ),
    ]
