# Generated by Django 5.2 on 2025-06-13 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_travaux', '0004_rename_acquition_dao_avisappeloffre_acquisition_dao'),
        ('document', '0012_remove_appeloffre_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisappeloffre',
            name='appel_offre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='document.appeloffre'),
        ),
    ]
