# Generated by Django 5.2 on 2025-06-27 12:55

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_travaux', '0005_alter_avisappeloffre_appel_offre'),
        ('document', '0012_remove_appeloffre_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consistenceTravaux', ckeditor.fields.RichTextField()),
                ('liste_prequalifie', ckeditor.fields.RichTextField()),
                ('provenance_materiaux', ckeditor.fields.RichTextField()),
                ('renseignements_necessaires', ckeditor.fields.RichTextField()),
                ('visite_travaux', ckeditor.fields.RichTextField()),
                ('renseignements_complementaires', ckeditor.fields.RichTextField()),
                ('langue_soumission', ckeditor.fields.RichTextField()),
                ('piecesAdminLocales', ckeditor.fields.RichTextField()),
                ('piecesAdminEtrangeres', ckeditor.fields.RichTextField()),
                ('refSoumissionnaire', ckeditor.fields.RichTextField()),
                ('personnel', ckeditor.fields.RichTextField()),
                ('materiels', ckeditor.fields.RichTextField()),
                ('organisation_methodologie', ckeditor.fields.RichTextField()),
                ('respect_formulaire', ckeditor.fields.RichTextField()),
                ('preuve_acceptation', ckeditor.fields.RichTextField()),
                ('commentaire_ccap', ckeditor.fields.RichTextField()),
                ('capacite_financiere', ckeditor.fields.RichTextField()),
                ('offreFinanciere', ckeditor.fields.RichTextField()),
                ('impots_taxes', ckeditor.fields.RichTextField()),
                ('prix_marche', ckeditor.fields.RichTextField()),
                ('monnaies_soumission', ckeditor.fields.RichTextField()),
                ('taux_change', ckeditor.fields.RichTextField()),
                ('validite_offre', ckeditor.fields.RichTextField()),
                ('montant_cautionnement', ckeditor.fields.RichTextField()),
                ('evaluation_offres', ckeditor.fields.RichTextField()),
                ('variante_techniques', ckeditor.fields.RichTextField()),
                ('reunion_preparatoire', ckeditor.fields.RichTextField()),
                ('soumission_en_ligne', ckeditor.fields.RichTextField()),
                ('date_heure_limite', ckeditor.fields.RichTextField()),
                ('ouverture_plis', ckeditor.fields.RichTextField()),
                ('qualification_soumissionaire', ckeditor.fields.RichTextField()),
                ('criteres_eliminatoires', ckeditor.fields.RichTextField()),
                ('criteres_essentiels', ckeditor.fields.RichTextField()),
                ('monnaie_retenu', ckeditor.fields.RichTextField()),
                ('mode_evaluation', ckeditor.fields.RichTextField()),
                ('ref_32_2_e', ckeditor.fields.RichTextField()),
                ('ref_32_2_g', ckeditor.fields.RichTextField()),
                ('ref33_1', ckeditor.fields.RichTextField()),
                ('ref_34_1', ckeditor.fields.RichTextField()),
                ('ref_34_2', ckeditor.fields.RichTextField()),
                ('ref_39_2', ckeditor.fields.RichTextField()),
                ('appel_offre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='document.appeloffre')),
            ],
        ),
    ]
