# Generated by Django 5.2 on 2025-06-30 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_travaux', '0006_rpao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpao',
            old_name='soumission_en_ligne',
            new_name='mode_soumission',
        ),
    ]
