# Generated by Django 5.2 on 2025-06-30 13:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_travaux', '0007_rename_soumission_en_ligne_rpao_mode_soumission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpao',
            name='liste_prequalifie',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rpao',
            name='renseignements_necessaires',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
