# Generated by Django 5.2 on 2025-07-08 15:15

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_travaux', '0011_rename_borderau_bpu_prix_unitaires'),
        ('document', '0012_remove_appeloffre_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DQE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dqe', ckeditor.fields.RichTextField()),
                ('appel_offre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='document.appeloffre')),
            ],
        ),
    ]
