# Generated by Django 5.2 on 2025-07-10 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_travaux', '0012_dqe'),
        ('document', '0012_remove_appeloffre_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo_moa')),
                ('appel_offre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='document.appeloffre')),
            ],
        ),
    ]
