# Generated by Django 5.2 on 2025-07-17 14:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_travaux', '0014_cctp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cctp',
            name='cctp_fichier',
            field=ckeditor.fields.RichTextField(default=2),
            preserve_default=False,
        ),
    ]
