# Generated by Django 5.2 on 2025-07-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_travaux', '0015_alter_cctp_cctp_fichier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cctp',
            old_name='cctp_fichier',
            new_name='clauses_techniques',
        ),
    ]
