# Generated by Django 5.2 on 2025-07-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_travaux', '0016_rename_cctp_fichier_cctp_clauses_techniques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisappeloffre',
            name='numero_moa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
