# Generated by Django 5.2 on 2026-04-08 02:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_travaux', '0018_avisappeloffre_acquisition_dao_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpao',
            name='ref_40',
            field=ckeditor.fields.RichTextField(default='Hello world'),
            preserve_default=False,
        ),
    ]
