# Generated by Django 5.2 on 2026-04-08 02:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_travaux', '0019_rpao_ref_40'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpao',
            name='soumission_en_ligne',
            field=ckeditor.fields.RichTextField(default='Le mode et le format de soumission des offres est le suivant'),
            preserve_default=False,
        ),
    ]
