# Generated by Django 5.2 on 2026-05-02 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_travaux', '0021_bpu_dqe'),
        ('document', '0012_remove_appeloffre_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpu_dqe',
            name='appel_offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.appeloffre'),
        ),
    ]
