# Generated by Django 5.2 on 2026-05-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_travaux', '0022_alter_bpu_dqe_appel_offre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccap',
            name='contractant',
            field=models.CharField(default='Le gouverneur', max_length=100),
            preserve_default=False,
        ),
    ]
