# Generated by Django 5.2 on 2026-08-09 12:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_travaux', '0023_ccap_contractant'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisappeloffre',
            name='translated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avisappeloffre',
            name='valide_en',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='avisappeloffre',
            name='acquisition_dao_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avisappeloffre',
            name='attribution_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avisappeloffre',
            name='caution_soumission_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avisappeloffre',
            name='consistence_travaux_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avisappeloffre',
            name='consultation_dossier_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avisappeloffre',
            name='cout_previsionnel_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avisappeloffre',
            name='critere_eliminatoire_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avisappeloffre',
            name='critere_essentielles_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avisappeloffre',
            name='delai_previsionnel_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avisappeloffre',
            name='financement_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avisappeloffre',
            name='mode_soumission_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='avisappeloffre',
            name='objet_appel_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avisappeloffre',
            name='ouverture_plis_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avisappeloffre',
            name='participation_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avisappeloffre',
            name='recevabilite_plis_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avisappeloffre',
            name='remise_offre_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avisappeloffre',
            name='renseignement_complementaires_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avisappeloffre',
            name='tranches_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
