# Generated by Django 5.2 on 2026-09-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_services_non_quantifiables', '0002_seed_pieces'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LettreInvitation',
        ),
    ]
