# Generated by Django 5.2 on 2026-09-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services_non_quantifiables', '0004_fix_piece0_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccap',
            name='definitions_attributions',
        ),
        migrations.AddField(
            model_name='ccap',
            name='autorite_liquidation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ccap',
            name='autorite_ordonnancement',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ccap',
            name='chef_service_marche',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ccap',
            name='cocontractant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ccap',
            name='contractant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ccap',
            name='control_externe',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ccap',
            name='ing_marche',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ccap',
            name='organisme_paiment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ccap',
            name='responsable_renseignement',
            field=models.CharField(default='', max_length=100),
        ),
    ]
