# Generated by Django 5.2 on 2026-08-13 11:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_conception_realisation', '0006_remove_rpao_adresse_depot_offres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avisappeloffre',
            name='mode_soumission',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='avisappeloffre',
            name='mode_soumission_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
