# Generated by Django 5.2 on 2026-08-17 16:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_conception_realisation', '0007_alter_avisappeloffre_mode_soumission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpao',
            name='criteres_eliminatoires',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='rpao',
            name='criteres_essentiels',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
