# Generated by Django 5.2 on 2026-08-18 03:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_conception_realisation', '0008_rpao_criteres_eliminatoires_rpao_criteres_essentiels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpao',
            name='criteres_essentiels',
        ),
        migrations.RemoveField(
            model_name='rpao',
            name='ref_25',
        ),
        migrations.AddField(
            model_name='rpao',
            name='sous_criteres_essentiels_prop_artistique',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='rpao',
            name='sous_criteres_essentiels_prop_technique',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
