# Generated by Django 5.2 on 2026-08-18 10:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_conception_realisation', '0009_remove_rpao_criteres_essentiels_remove_rpao_ref_25_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rpao',
            name='sous_criteres_essentiels_prop_technique',
        ),
        migrations.AddField(
            model_name='rpao',
            name='notes_financiere_generale',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='rpao',
            name='sous_criteres_technique_delais_capacite',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='rpao',
            name='sous_criteres_technique_materiel',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='rpao',
            name='sous_criteres_technique_personnel',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='rpao',
            name='sous_criteres_technique_references',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
