# Generated by Django 5.2 on 2026-08-18 14:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_conception_realisation', '0010_remove_rpao_sous_criteres_essentiels_prop_technique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccap',
            name='reception_provisoire',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
