# Generated by Django 5.2 on 2026-08-18 15:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_conception_realisation', '0011_ccap_reception_provisoire'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccap',
            name='montant_marche',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccap',
            name='montant_phase1',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ccap',
            name='montant_phase2',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
