# Generated by Django 5.2 on 2026-08-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_conception_realisation', '0012_ccap_montant_marche_alter_ccap_montant_phase1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudeprealable',
            name='etude_prealable_date',
        ),
        migrations.RemoveField(
            model_name='etudeprealable',
            name='etude_prealable_description',
        ),
        migrations.RemoveField(
            model_name='etudeprealable',
            name='etude_prealable_maitre_oeuvre',
        ),
        migrations.RemoveField(
            model_name='etudeprealable',
            name='etude_prealable_references_marche',
        ),
        migrations.RemoveField(
            model_name='etudeprealable',
            name='etude_prealable_type',
        ),
    ]
