# Generated by Django 5.2 on 2026-08-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_conception_realisation', '0013_remove_etudeprealable_etude_prealable_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EtudePrealable',
        ),
    ]
